version: '3.3'
services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    build:
      context: ./db
    volumes:
      - db:/var/lib/postgresql/data/
    env_file:
      - ./.env
    networks:
      - network
    ports:
      - 5432:5432
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
  graphql:
    image: graphql
    container_name: graphql
    restart: always
    build:
      context: ./graphql
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - network
    ports:
      - 5433:5433
    command: ["--connection", "${DATABASE_URL}", "--port", "5433", "--schema", "public", "--append-plugins", "postgraphile-plugin-connection-filter,@graphile-contrib/pg-simplify-inflector", "--cors"]
volumes:
  db:
networks:
  network: